### ISSUE TITLE
what is kerga in random_attack

### ISSUE THREAD

**Issue by mgh790** [Kautenja/robust-graph-convolutional-networks-against-adversarial-attacks-implementation#10]
hi.  in your random-attack.ipynb file, 
you had mentioned to "kegra.utils import load_data, preprocess_adj, get_splits".
i don't understand what is kegra? how can we add it to the code?

**Comment by Kautenja** [comment]
It's been a while since I worked on this, but I think kegra comes from here: https://github.com/tkipf/keras-gcn

**Comment by mgh790** [comment]
> It's been a while since I worked on this, but I think kegra comes from here: https://github.com/tkipf/keras-gcn

but in your code , you added a new variable as attack_edges in load_ data fucntion, which is not in the keras-gcn.
  "load_data('data/cora/', dataset='cora', attack_edges=attack_edges(0))"

**Comment by Kautenja** [comment]
ah, yea i forked it with that change: https://github.com/Kautenja/keras-gcn

**Comment by mgh790** [comment]
> ah, yea i forked it with that change: https://github.com/Kautenja/keras-gcn

tnx alot
